const routes=[
    {
        path:'/index',
        name:'index',
        component:()=>import('@/views/index/index'),
        children:[
            {
                path:'home',
                meta:{
                    requires:true
                },

                component:()=>import('@/views/index/home/home')
            },
            {
                path:'my',
                meta:{
                    requires:true
                },
                component:()=>import('@/views/index/my/my')
            }
        ]
    },
    {
        path:'/changepwd',
        name:'changepwd',
        component:()=>import('@/views/changepwd/changepwd')
    },
    {
        path:'/Collection',
        name:'Collection',
        component:()=>import('@/views/Collection/Collection')
    },
    {
        path:'/comment',
        name:'comment',
        component:()=>import('@/views/comment/comment')
    },
    {
        path:'/login',
        name:'login',
        component:()=>import('@/views/login/login')
    },
    {
        path:'/perin',
        name:'perin',
        component:()=>import('@/views/perin/perin')
    },
    {
        path:'/register',
        name:'register',
        component:()=>import('@/views/register/register')
    },
    {
        path:"/",
        redirect:'/index'
    }
];
export default routes;